# docker compose -f mongo-docker-compose.yaml up

version: '3.8'

services:
  mongodb:
    image: mongo:latest # not change "mongo" name
    container_name: geomongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminuser
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    ports:
      - 27017:27017
    volumes:
      - ./data:/data

  mongo-express:
    image: mongo-express:latest # not change "mongo-express" name
    container_name: geomongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: adminuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpass
      ME_CONFIG_MONGODB_URL: mongodb://adminuser:adminpass@geomongo:27017/

volumes:
  data: {}

networks:
  default:
    name: geomongo_network
